install:
	mkdir -p $$HOME/.config/karabiner/assets/complex_modifications/
	cp ultimate_macOS.json $$HOME/.config/karabiner/assets/complex_modifications/

all:
	mkdir -p $$HOME/.config/karabiner/
	cp karabiner.json $$HOME/.config/karabiner/

.PHONY: install,all